var input = require("fs").readFileSync("stdin", "utf8");
var lines = input.split("\n");

process.stdout.write("---------------------------------------\n");
process.stdout.write("|        Roberto                      |\n");
process.stdout.write("|                                     |\n");
process.stdout.write("|        5786                         |\n");
process.stdout.write("|                                     |\n");
process.stdout.write("|        UNIFEI                       |\n");
process.stdout.write("---------------------------------------\n");